[package]
authors = ["Thomas Wickham <mackwic@gmail.com>"]
edition = "2018"
name = "monitor-websites"
version = "0.1.0"
[dependencies]
chrono = "*"
fern = { version = "*", features = [ "colored" ] }
log = "*"
reqwest = "*"
