
# websites = []

# For Development: Stop after iteration N
stop_after_iteration = 10
# For Production: Unless run_forever is true, in this case... run forever
run_forever = false

# Number of websites to fetch in parallel
parallel_fetch = 10

# interval (in milliseconds between each fetching
interval_between_fetch = 5_000
